### ISSUE TITLE
HTML lang attribute causes built application to fail on startup with some widgets

### ISSUE THREAD

**Issue by hlavacek** [bryanforbes/generator-dojo#4]
Hello,

When I use the dijit/Dialog in my web page like this 

```
<div class="dijitHidden">
    <div data-dojo-type="dijit/Dialog" id="myDialog" title="Name and Address">
        My Sample Dialog
    </div>
</div>
```

And then use just the parser to parse the html file and show the dialog in my main.js file:

```
define([
    'exports', 'dojo/ready', 'dojo/parser', 'dijit/registry', 'dijit/Dialog'
], function (widgettest, ready, parser, registry) {
    widgettest.init = function () {
    };

    ready(function() {
        parser.parse();
        registry.byId('myDialog').show();
        console.log('ready');
    });
});
```

The application is working fine in the "not compiled" version running with grunt server and shows the dialog on startup. But when I try to run it built with grunt server:dist, it won't show any error, but also the dialog isn't shown. 

After replacing the compressed js files with uncompressed ones I've find out that the parser fails to parse the page, as it cannot find the localisation resources for the dialog (some reference in the code was resulting in undefined).

A simple fix to this issue was to change the lang attribute in the html page from:

```
<html lang="en">
```

to

```
<html lang="en-us">

```

The dialog was then working fine also in the built version of the application. 

I'm not sure whether this is a problem in the dojo build or the component itself, but it was quite annoying to have built application not working with absolutely no error shown. Would it be possible to change this also directly in the generator to avoid the issue?

**Comment by bryanforbes** [comment]
Thanks for the report. This is due to a change in how the parser works in 1.9: it now looks for the `lang` attribute on parent nodes and sets created widgets' `lang` property to that string. If `navigator.language` (which `dojo/i18n`) and the `lang` attribute differ, lookup for nls bundles will fail for widgets. Because of this change, simply changing `lang` to `"en-us"` will not work for every locale, so I have removed the attribute. I will make a new release soon with this fix.

Additionally, using `dojo/ready` with the generator is not needed and discouraged. `dojo/ready` was a way to be when all dependencies were loaded, informed when the DOM was ready to be modified, and when the parser was complete. There are better (and less magic) ways to accomplish what `dojo/ready` used to do:
1. Dependency loading is now handled by AMD and application bootstrap dependencies should be dependencies of `main.js`. The factory function won't run until all dependencies are loaded.
2. Adding `"dojo/domReady!"` as a dependency of `main.js` will delay the running of the factory function until the DOM is ready. Alternatively, you could place all declarative widgets before the script tags in `index.html` and ignore the `dojo/domReady!` dependency.
3. Including all modules that will be created by the parser in the dependency list of `main.js` (you are doing this) and manually running the parser (you are also doing this) will run the parser in synchronous mode. This means that as soon as the parser is done executing, widgets are ready.

In addition, as soon as `main.js` is ready (dependencies loaded), `init()` is called. This means that simply adding `dojo/domReady!` as a dependency of `main.js` and moving the code in the ready callback into the body of `init()` will accomplish the same result as what you are trying to do.
