### ISSUE TITLE
Feature Request: Maqetta Directory Layout

### ISSUE THREAD

**Issue by ceeroover** [bryanforbes/generator-dojo#5]
Would it be possible to add an option to make the generator compatible with the Maqetta directory structure, that one could easily download the files, add it to the src directory and run the build?

**Comment by bryanforbes** [comment]
I've chosen a very generic directory structure that I and several other developers have used for many years and works for many different types of web apps, so I'm fairly hesitant to change it. That being said, I'm unsure what the Maqetta directory structure is, so any links outlining it would help. If it is close, a flag may be an option. Thanks!

**Comment by ceeroover** [comment]
I've uploaded a small example.

https://github.com/ceeroover/maqetta-mindless

It's the workspace one ends up after creating a new project. The main files are placed in root (index.html, app.js). Any custom scripts are meant to be placed within lib/custom.
package.json and server.js are templates I added to start the project with node.

**Comment by bryanforbes** [comment]
Thanks for the example. After looking at the directory layout, I've decided not to support the Maqetta directory structure for a few reasons:
1. It seems to use a custom directory structure where the Dojo toolkit is placed in a directory (`dojo`) that is a sibling to application code instead of the toolkit contents being placed as siblings of application code. This leads to a very complex (and mostly unnecessary if packages are siblings to each other) [loader configuration](https://github.com/ceeroover/maqetta-mindless/blob/master/index.html#L7).
2. The complex configuration also requires a complex build profile since the Dojo build tool, by default, copies all packages into a flat structure (hence the chosen directory structure for this project). Maqetta may take care of building for you, but if this project is going to support a secondary directory structure, I feel it must handle building without an external tool.
3. With [IBM suspending work on Maqetta](https://groups.google.com/forum/#!topic/maqetta-users/dLGzdERrkG8) (with no one picking up the torch to lead the maqetta community) and [hosting going away](https://groups.google.com/forum/#!topic/maqetta-users/0M0da6576Cg) plus my limited time, I'd rather not support a dying project's directory structure.
