### ISSUE TITLE
Install bower dependencies in a bower_components folder?

### ISSUE THREAD

**Issue by PunkChameleon** [bryanforbes/generator-dojo#9]
Is it possible to configure this to install the bower_components in their own folder, than build it accordingly?

Also, when I'm trying to add a new component (LESS in this case), I'm getting the following error during the build -- 

```
 Module not tagged as pure AMD yet it contains AMD API applications
```

What are the steps for adding new components? I realize some of this may be more dojo-question oriented than just this generator -- thought it would be a good place to reach out though!

Thanks again for this app -- it's been a lifesaver!

**Comment by neonstalwart** [comment]
the components are intentionally _not_ added to `bower_components` because this makes them simpler to consume them as AMD modules.  if you really want to change this, then adjust/remove the `.bowerrc` file that gets generated in your project but be warned that this will put dojo, dijit, dojox, etc in the `bower_components` directory too.  if you don't have a really compelling reason to use `bower_components` then i suggest that you should leave `.bowerrc` as it is because there are good reasons _not_ to use `bower_components` in this type of project - the main one is that it makes it simpler to consume the components as AMD modules.

i expect that the issue you're seeing with LESS is just a warning and can be ignored but if it bothers you then:
1. LESS shouldn't be part of your application code - it's a pre-processor.  remove it from the list of packages in your profile then the build won't find it.
2. assuming you ignore my first point... you need to add some configuration to the LESS package in your build profile so that the build understands which files are AMD modules.  you can do this by inlining something like this (you'd need to fill in the right values as needed):

``` js
name: 'LESS',
location: ' ... ',
main: ' ... ',
resourceTags: {
    test: function (filename) {
        // anything that has "test" in the filename is a test
        return (/\/test\//).test(filename);
    },
    amd: function (filename) {
        // anything that ends in .js is an AMD module
        return (/\.js$/).test(filename);
    }
}
```

...and here's something you didn't ask for but based on experience i'm going to suggest switching to stylus rather than LESS.

**Comment by PunkChameleon** [comment]
Thanks for the notes about less -- was thinking about it more clearly and realized I only needed it pre-build.

As for the bower_components, I am just used to see it that way (and being able to easily .gitignore the entire directory) as per the bower documentation. Though I do understand the AMD approach and am trying to embrace it :smile: 

Thanks!

**Comment by PunkChameleon** [comment]
Decided to keep current structure. Closing!
